export const FRIDGE_UPDATE_FOOD = 'FRIDGE_UPDATE_FOOD';
export const FRIDGE_UPDATE_STOCK = 'FRIDGE_UPDATE_STOCK'; 
export const FRIDGE_UPDATE_STOCK_BYTYPE = 'FRIDGE_UPDATE_STOCK_BYTYPE';

export const FRIDGE_ADD_FOOD = 'FRIDGE_ADD_FOOD';
export const FRIDGE_ADD_STOCK = 'FRIDGE_ADD_STOCK';
export const FRIDGE_ADD_STOCK_BYTYPE = 'FRIDGE_ADD_STOCK_BYTYPE';
export const FRIDGE_SET_STOCK = 'FRIDGE_SET_STOCK';
export const FRIDGE_SET_STOCK_BYTYPE = 'FRIDGE_SET_STOCK_BYTYPE';
export const FRIDGE_DELETE_STOCK = 'FRIDGE_DELETE_STOCK';
export const FRIDGE_DELETE_STOCK_BYTYPE = 'FRIDGE_DELETE_STOCK_BYTYPE';