export const FRIDGE_UPDATE_FOOD = 'FRIDGE_UPDATE_FOOD';
export const FRIDGE_UPDATE_STOCK = 'FRIDGE_UPDATE_STOCK'; 
export const FRIDGE_ADD_FOOD = 'FRIDGE_ADD_FOOD';
export const FRIDGE_ADD_STOCK = 'FRIDGE_ADD_STOCK';
export const FRIDGE_ADD_STOCK_SET = 'FRIDGE_ADD_STOCK_SET';
export const FRIDGE_DELETE_STOCK = 'FRIDGE_DELETE_STOCK';